apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieservice
  namespace: watcherz
  labels:
    app: movieservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movieservice
  template:
    metadata:
      labels:
        app: movieservice
    spec:
      restartPolicy: Always
      containers:
        - name: movieservice
          image:  registry.vimuens.nl/movieservice:latest
          imagePullPolicy: Always
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://discoveryservice:8761/eureka
            - name: eureka.instance.prefer-ip-address
              value: "true"
            - name: server.port
              value: "9090"
          ports:
            - containerPort: 8082